import Vue from 'vue'
import {
    Aside,
    Button,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Carousel,
    CarouselItem,
    Col,
    Container,
    DatePicker,
    Dialog,
    Divider,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Header,
    Collapse,
    CollapseItem,
    Form,
    FormItem,
    Footer,
    Input,
    InputNumber,
    Link,
    Loading,
    Main,
    Message,
    MessageBox,
    Menu,
    MenuItem,
    Option,
    Pagination,
    Row,
    Select,
    Switch,
    Table,
    TableColumn,
    Tooltip,
    Tree,
    Transfer
} from 'element-ui'

Vue.use(Button)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Footer)
Vue.use(Input)
Vue.use(Container)
Vue.use(Dialog)
Vue.use(Aside)
Vue.use(Header)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tooltip)
Vue.use(Option)
Vue.use(Select)
Vue.use(Row)
Vue.use(Col)
Vue.use(InputNumber)
Vue.use(DatePicker)
Vue.use(Pagination)
Vue.use(Tree)
Vue.use(Link)
Vue.use(Loading)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Switch)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Divider)
Vue.use(Transfer)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
